### ISSUE TITLE
Maven Wrapper mit aufnehmen

### ISSUE THREAD

**Issue by mvitz** [ewolff/cheatsheets-DE#4]
Ich denke ein zusätzlicher Abschnitt über den Maven Wrapper wäre noch ganz gut. Spring Boot liefert diesen auch mit.

Es braucht imho nur eine kurze Erläuterung, dass der Maven Wrapper die beiden Scripts `mvnw` und `mvnw.cmd` mitbringt (und zwei Dateien in `.mvn`). Wenn man diese Scripts anstelle von `mvn` nutzt lädt der Wrapper Maven herunter (Quellort steht in `.mvn/wrapper/maven-wrapper.properties`), installiert diesen nach `~/.m2/wrapper/dists/` und nutzt anschließend genau diese Maven Installation. Referenzieren mehrere Projekte dieselbe Maven Version wird sich diese allerdings geteilt.

**Comment by ewolff** [comment]
Danke. Nutzen die Wrapper dann eigentlich das settings.xml und das Repo im .m2 ?
Vielleicht noch kurz zum Hintergrund: Ich will für die Demos unter http://ewolff.com/microservices-demos.html eine Hilfstellung u.a. für Maven geben. Die Demos nutzen im Moment keinen Maven-Wrapper, sondern setzten eine Maven-Installation voraus. Ich bin nicht sicher, ob ich das komplett umstellen sollte.

**Comment by mvitz** [comment]
Ja tut der Wrapper. Im Grunde stellt er primär sicher das immer die gleiche Version von Maven genutzt wird und erleichtert die Installation.

**Comment by ewolff** [comment]
Ich habe den Maven-Wrapper aufgenommen, aber nur aus einer Benutzersicht. D.h. ich habe nicht erläutert, wie man den Maven-Wrapper einrichtet. Ich denke, das ist aber ausreichend.

**Comment by ewolff** [comment]
...und danke für den Tipp - das ist sicher eine Vereinfachung! :-)
